### PR TITLE
Bugfix #19: Replaced dnd implementation and improved it

### LINKED ISSUE #19: Redo file drag-and-drop
## Task description

****

Replace `tkinterDnD` which led to major errors and bugs and replace it with a working drag-and-drop interface that allows the user to load `BAM` and `FASTQ` files via drag-and-drop.

## Additional context

https://stackoverflow.com/questions/44887576/how-can-i-create-a-drag-and-drop-interface

### PR DESCRIPTION
**Pull request by FinnSpr**
## Motivation

Resolves #19 

## Changes

Because of major issues with the old `tkinterDnD` module, I've replaced it using the `tkinterdnd2` module from [here](https://github.com/pmgagne/tkinterdnd2). This one should work on Windows, Mac and Unix. In addition, I've fixed some issues concerning the file acceptance of certain files in the old version because some file paths had brackets, some others not and the way of handling this wasn't good. Finally, I've made it possible to load files without names before the extension via drag-and-drop (e. g. `.txt` or `.fastq`).

## Testing

I've tried it out for many different paths, files and for files without a name. It worked for me.

## Additional context

Please test this thoroughly! It would be great if you could test the new drag-and-drop implementation for as many different files with different names, locations (e. g. desktop) and for multiple files at once (should be handled so that the first file will be detected).

### Important:
Files without names like `.txt` or `.fastq` have to be detected in a dirty way. The way consists of going through the absolute file path from the back and stopping when detecting the first `/` symbol. This works on my Windows machine, but there could be different separators for other OS. However, it would not be that bad if one could not load such files via dnd because selecting those when browsing the explorer works.

### CODE REVIEW

**Review by RTapiaSE — COMMENTED** [review]
Unfortunately, the Code still does not works/compiles for Mac users. The previous error  still exists: (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). It is not a problem of the code itself, it's a problem of how the code in computers that have this kind of architecture is compiled. We need to find a way to make this work without changing the code itself (e.g. writing aa documentation on how to use Anaconda to compile the code).

**Comment by FinnSpr** [comment]
Ok, that's bad, but I'm pretty sure that we can solve this because, as you just said, the code or module should not be the cause of this problem. Although this may be some unfunny work for you to do, it would be great if you could try to fix this problem on your machine because for me it is not possible to do so. If you search for this problem, there are many hits appearing, so I recommend to follow their instructions and try them out until you can run the application. After you managed to solve it, I will immediately update the information about how to install the modules and get the program running.

One link that may be helpful: https://apple.stackexchange.com/questions/436801/m1-mac-mach-o-file-but-is-an-incompatible-architecture-have-x86-64-need-a

**Review by RTapiaSE — COMMENTED** [review]
I have solved the problem by installing the tkinterdnd2-universal package. I will add the set up link with further instructions on our README.md file.

**Review by RTapiaSE — APPROVED** [review]
The README.md File has been update it. Now, it is ready to merge.

**Review by LukasGWolf — APPROVED** [review]

**Pull request merged**
